-- AlterTable
ALTER TABLE "User" ADD COLUMN     "avatarOffsetX" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "avatarOffsetY" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "avatarRotation" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "avatarZoom" DOUBLE PRECISION DEFAULT 1.0;
